routes/frontend.php
<?php
Route::get("/", "HomeController@index")->name('home.index');

Route::get('/page/{slug}', 'HomeController@customPage')->name('home.custom.page');

Route::get('/user-login', 'UserLoginController@loginView')->name('user.login');
Route::post('/user-login-submit', 'UserLoginController@loginSubmit')->name('user.login.submit');

Route::post('/user-registration-submit', 'UserController@store')->name('user.registration.submit');


Route::get('user/login/facebook', 'UserLoginController@redirectToProvider')->name('user.facebook.login');
Route::get('user/login/facebook/callback', 'UserLoginController@handleProviderCallback');

Route::get('user/login/google', 'UserLoginController@redirectToProviderGoogle')->name('user.google.login');
Route::get('user/login/google/callback', 'UserLoginController@handleProviderGoogleCallback');

Route::get('/product-detail/{slug}', 'frontend\ProductDetailController@index')->name('product.detail');

Route::group(['middleware' => 'authCeckUser'], function () {
    Route::resource("/user", "UserController");
    Route::get('/user-logout', 'UserLoginController@logout')->name('user.logout');

    Route::get('/become-vendor', 'frontend\UserDashboardController@BecomeVendor')->name('frontend.become.vendor');
    Route::post('/vendor/subscription', 'frontend\UserDashboardController@vendorSubscription')->name('frontend.vendor.subscription');
});

routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});

include('parvez.php');
include('frontend.php');

Route::get('/admin-login','AdminLoginController@loginView')->name('admin.login');
Route::post('/admin-login-submit','AdminLoginController@loginSubmit')->name('admin.login.submit');

Route::group(['middleware'=>'authCheck'],function (){
	
	 Route::get("/dashboard","DashboardController@index");

    Route::resource("/activity","ActivityController");

    Route::resource("/module","ModuleController");

    Route::resource("/role","RoleController");

    Route::resource("/user","UserController");

    Route::get('role-access',"RoleAccessController@index")->name('role.access');
    Route::post('roleAclSetup', 'RoleAccessController@roleAclSetup');
    Route::post('roleacl', 'RoleAccessController@save');

    Route::get('user-access', 'UserAccessController@index')->name('user.access');
    Route::post('userAclSetup', 'UserAccessController@userAclSetup');
    Route::post('useracl', 'UserAccessController@save');

    Route::get('/backend',function(){
        return view('backend.demo');
    });

    Route::get('/logout','AdminLoginController@logout')->name('admin.logout');

    Route::get('/dashboard',function(){
        return view('backend.demo');
    })->name('backend.dashboard');
    
    Route::get('/form',function(){
        return view('backend.form');
    });

    Route::resource("/discount", "DiscountController");
    Route::post('get-discount-user-list', 'DiscountController@getDiscountUserList')->name('discount-user.list');
    Route::resource("/shipping-option", "ShippingOptionController");
    Route::resource("/shop-setting", "ShopSettingController");
    Route::get("/show-logo-banner/{action}/{id}", "ShopSettingController@showLogoBanner")->name("show-logo-banner.show");
    Route::resource("/vendor-page", "VendorPageController");
    Route::resource("/translation-language", "TranslationLanguageController");
    Route::resource("/countries", "CountriesController");
    Route::resource("/state", "StateController");
    Route::resource("/city", "CityController");

    Route::resource("store-review","StoreReviewController");
    Route::get('orders','OrderController@index')->name('backend.order.view');
    Route::get('orders-details/{id}/{action?}','OrderController@orderDetails')->name('backend.order.details');
    Route::post('orders-status-change','OrderController@orderStatusChange')->name('backend.orders-status-change');

    Route::resource('payment-gateway','PaymentGatewayController');
    Route::resource('currencys','CurrencyController');
    Route::resource('email-configuration','EmailConfigurationController');
    Route::resource('products','ProductController');

    Route::get('products-gallery/{slug}','ProductGalleryController@galleryImage')->name('product.gallery');
    Route::post('products-gallery/product.gallery.store','ProductGalleryController@galleryImageStore')->name('product.gallery.store');
    Route::get('products-gallery/delete/{id}','ProductGalleryController@galleryImageDelete')->name('product.gallery.delete');

    //product route start
    Route::get('partho-product/create','ParthoProductController@ProductCreate')->name('product_create');
    Route::get('partho-product/list','ParthoProductController@ProductList')->name('product_list');
    Route::get('partho-product/details/{id}','ParthoProductController@productDetails')->name('product_details');
    Route::get('partho-product/edit/{id}','ParthoProductController@productEdit')->name('product_edit');
    Route::post('partho-product/store/','ParthoProductController@productStore')->name('product_store');
    Route::post('partho-product/update/','ParthoProductController@productUpdate')->name('product_update');
    Route::get('partho-import/product','ParthoProductController@importProduct')->name('import_product');
    //product route end

    Route::resource('vendor-subscription-plan','VendorSubscriptionPlansController');

//Ajax Route
    Route::post('get/subcategory','AjaxController@subCategory')->name('get.subcategory');
include('farhan.php');
});

resources/views/backend/include/admin-menu.blade.php
<li class="fl-menu-item">
    <a href="index.html" class="fl-menu-link active">
        <i class="menu-item-icon icon ion-ios-home-outline tx-24"></i>
        <span class="menu-item-label">Dashboard</span>
    </a><!-- fl-menu-link -->
</li><!-- fl-menu-item -->
<li class="fl-menu-item">
    <a href="" class="fl-menu-link">
        <i class="menu-item-icon icon ion-ios-email-outline tx-24"></i>
        <span class="menu-item-label">Mailbox</span>
    </a><!-- fl-menu-link -->
</li><!-- fl-menu-item -->
<li class="fl-menu-item">
    <a href="#" class="fl-menu-link with-sub">
        <i class="menu-item-icon icon ion-ios-photos-outline tx-20"></i>
        <span class="menu-item-label">Cards &amp; Widgets</span>
    </a><!-- fl-menu-link -->
    <ul class="fl-menu-sub">
        <li class="sub-item"><a href="#" class="sub-link">Dashboard</a></li>
        <li class="sub-item"><a href="#" class="sub-link">Blog &amp; Social Media</a></li>
        <li class="sub-item"><a href="#" class="sub-link">Shop &amp; Listing</a></li>
    </ul>
</li>
<li class="fl-menu-item">
    <a href="#" class="fl-menu-link with-sub">
        <i class="menu-item-icon icon ion-ios-photos-outline tx-20"></i>
        <span class="menu-item-label">Extra</span>
    </a><!-- fl-menu-link -->
    <ul class="fl-menu-sub">
        <li class="sub-item"><a href="{{route('extra.form1')}}" class="sub-link">Table</a></li>
        <li class="sub-item"><a href="{{route('extra.form2')}}" class="sub-link">Form</a></li>
    </ul>
</li>





{{-- @if(!empty($aclList[6][1])) --}}
<li class="fl-menu-item">
    <a href="#" class="fl-menu-link with-sub">
        <i class="menu-item-icon icon ion-ios-photos-outline tx-20"></i>
        <span class="menu-item-label">User Management</span>
    </a><!-- fl-menu-link -->
    <ul class="fl-menu-sub">
        <li class="sub-item"><a href="{{route('user.index')}}" class="sub-link">List</a></li>
        <li class="sub-item"><a href="{{route('user.create')}}" class="sub-link">Create</a></li>
    </ul>
</li>
{{-- @endif --}}

{{-- @if(!empty($aclList[1][1])) --}}
<li class="fl-menu-item">
    <a href="#" class="fl-menu-link with-sub">
        <i class="menu-item-icon icon ion-ios-photos-outline tx-20"></i>
        <span class="menu-item-label">Role Management</span>
    </a><!-- fl-menu-link -->
    <ul class="fl-menu-sub">
        <li class="sub-item"><a href="{{route('role.index')}}" class="sub-link">List</a></li>
        <li class="sub-item"><a href="{{route('role.create')}}" class="sub-link">Create</a></li>
    </ul>
</li>
{{-- @endif --}}

{{-- @if(!empty($aclList[2][1])) --}}
<li class="fl-menu-item">
    <a href="#" class="fl-menu-link with-sub">
        <i class="menu-item-icon icon ion-ios-photos-outline tx-20"></i>
        <span class="menu-item-label">Role Access Control</span>
    </a><!-- fl-menu-link -->
    <ul class="fl-menu-sub">
        <li class="sub-item"><a href="{{route('role.access')}}" class="sub-link">Create</a></li>
    </ul>
</li>
{{-- @endif --}}

{{-- @if(!empty($aclList[3][1])) --}}
<li class="fl-menu-item">
    <a href="#" class="fl-menu-link with-sub">
        <i class="menu-item-icon icon ion-ios-photos-outline tx-20"></i>
        <span class="menu-item-label">User Access Control</span>
    </a><!-- fl-menu-link -->
    <ul class="fl-menu-sub">
        <li class="sub-item"><a href="{{route('user.access')}}" class="sub-link">Create</a></li>
    </ul>
</li>
{{-- @endif --}}

{{-- @if(!empty($aclList[4][1])) --}}
<li class="fl-menu-item">
    <a href="#" class="fl-menu-link with-sub">
        <i class="menu-item-icon icon ion-ios-photos-outline tx-20"></i>
        <span class="menu-item-label">Module Management</span>
    </a><!-- fl-menu-link -->
    <ul class="fl-menu-sub">
        <li class="sub-item"><a href="{{route('module.index')}}" class="sub-link">List</a></li>
        <li class="sub-item"><a href="{{route('module.create')}}" class="sub-link">Create</a></li>
    </ul>
</li>
{{-- @endif --}}

{{-- @if(!empty($aclList[5][1])) --}}
<li class="fl-menu-item">
    <a href="#" class="fl-menu-link with-sub">
        <i class="menu-item-icon icon ion-ios-photos-outline tx-20"></i>
        <span class="menu-item-label">Activity Management</span>
    </a><!-- fl-menu-link -->
    <ul class="fl-menu-sub">
        <li class="sub-item"><a href="{{route('activity.index')}}" class="sub-link">List</a></li>
        <li class="sub-item"><a href="{{route('activity.create')}}" class="sub-link">Create</a></li>
    </ul>
</li>
{{-- @endif --}}

@include("backend.include.farhan")
@include("backend.include.lemon")
@include("backend.include.partho")
@include("backend.include.miraj")

resources/views/backend/include/errormsg.blade.php
@if(Session::has('success'))
    <script>
        var msg ='{{ Session::get("success") }}';
        Swal.fire(msg, "", "success");
    </script>
@endif
@if(Session::has('error'))
    <script>
        var msg ='{{Session::get("error")}}';
        Swal.fire(msg, "", "error");
    </script>
@endif

resources/views/backend/include/farhan.blade.php
<li class="fl-menu-item">
    <a href="#"
        class="fl-menu-link with-sub @if($routeName == 'category.index'||$routeName == 'brand.index')active @endif">
        <i class="menu-item-icon icon ion-ios-photos-outline tx-20"></i>
        <span class="menu-item-label">Catalog Management</span>
    </a><!-- fl-menu-link -->
    <ul class="fl-menu-sub">
        <li class="sub-item"><a href="{{route('category.index')}}" class="sub-link">Categories</a></li>
        <li class="sub-item"><a href="{{route('brand.index')}}" class="sub-link">Brand</a></li>
    </ul>
</li>

<li class="fl-menu-item">
    <a href="#"
        class="fl-menu-link with-sub @if($routeName == 'pages.index'||$routeName == 'navigation.index'||$routeName == 'home-page-banner.index'||$routeName == 'social.link.edit' ||$routeName == 'advertisement.edit'||$routeName == 'advertisement.second.edit') active @endif">
        <i class="menu-item-icon icon ion-ios-photos-outline tx-20"></i>
        <span class="menu-item-label">Content Management</span>
    </a><!-- fl-menu-link -->
    <ul class="fl-menu-sub">
        <li class="sub-item"><a href="{{route('pages.index')}}" class="sub-link">Page</a></li>
        <li class="sub-item"><a href="{{route('navigation.index')}}" class="sub-link">Navigation</a></li>
        <li class="sub-item"><a href="{{route('home-page-banner.index')}}" class="sub-link">Home Page Banner</a></li>
        <li class="sub-item"><a href="{{route('social.link.edit')}}" class="sub-link">Social Link</a></li>
        <li class="sub-item"><a href="{{route('site.setting.edit')}}" class="sub-link">Site Settings</a></li>
        <li class="sub-item"><a href="{{route('advertisement.edit',"banner_portrait_top")}}"
                class="sub-link">Advertisemet 1</a></li>
        <li class="sub-item"><a href="{{route('advertisement.edit',"banner_portrait_bottom")}}"
                class="sub-link">Advertisemet 2</a></li>
        <li class="sub-item"><a href="{{route('advertisement.edit',"promotion_offer_first")}}"
                class="sub-link">Promotion First</a></li>
        <li class="sub-item"><a href="{{route('advertisement.edit',"promotion_offer_second")}}"
                class="sub-link">Promotion
                Second</a></li>
        <li class="sub-item"><a href="{{route('advertisement.edit',"promotion_offer_third")}}"
                class="sub-link">Promotion
                Third</a></li>
    </ul>
</li>

<li class="fl-menu-item">
    <a href="#" class="fl-menu-link with-sub @if($routeName == 'social-login-access.index') active @endif">
        <i class="menu-item-icon icon ion-ios-photos-outline tx-20"></i>
        <span class="menu-item-label">Social Login</span>
    </a><!-- fl-menu-link -->
    <ul class="fl-menu-sub">
        <li class="sub-item"><a href="{{route('social-login-access.index')}}" class="sub-link">Social Login Access</a>
        </li>
    </ul>
</li>

<li class="fl-menu-item">
    <a href="#" class="fl-menu-link with-sub @if($routeName == 'home.setup.edit') active @endif">
        <i class="menu-item-icon icon ion-ios-photos-outline tx-20"></i>
        <span class="menu-item-label">Home Setup</span>
    </a><!-- fl-menu-link -->
    <ul class="fl-menu-sub">
        <li class="sub-item"><a href="{{route('home.setup.edit')}}" class="sub-link">Seleted Category</a>
        </li>
    </ul>
</li>

resources/views/backend/include/footer.blade.php
<footer class="fl-footer">
    <div class="footer-left">
      <div class="mg-b-2">Copyright © 2020 FEITS LTD. All Rights Reserved.</div>
     
    </div>
    <div class="footer-right d-flex align-items-center">
      <span class="tx-uppercase mg-r-10">Share:</span>
      <a target="_blank" class="pd-x-5" href=""><i class="fab fa-facebook tx-20"></i></a>
      <a target="_blank" class="pd-x-5" href=""><i class="fab fa-twitter tx-20"></i></a>
    </div>
</footer>

resources/views/backend/include/header.blade.php
<div class="fl-header">
    <div class="fl-header-left">
        <div class="navicon-left hidden-md-down"><a id="btnLeftMenu" href=""><i class="fas fa-bars"></i></a></div>
        <div class="navicon-left hidden-lg-up"><a id="btnLeftMenuMobile" href=""><i class="fas fa-bars"></i></a></div>
    </div><!-- fl-header-left -->
    <div class="fl-header-right">
        <nav class="nav">
            <div class="dropdown">
                <a href="" class="nav-link pd-x-7 pos-relative" data-toggle="dropdown">
                    <i class="icon ion-ios-email-outline tx-24"></i>
                    <!-- start: if statement -->
                    <span class="square-8 bg-danger pos-absolute t-15 r-0 rounded-circle"></span>
                    <!-- end: if statement -->
                </a>
                <div class="dropdown-menu dropdown-menu-header">
                    <div class="dropdown-menu-label">
                        <label>Messages</label>
                        <a href="">+ Add New Message</a>
                    </div><!-- d-flex -->

                    <div class="media-list">
                        <!-- loop starts here -->
                        <a href="" class="media-list-link">
                            <div class="media">
                                <img src="https://via.placeholder.com/500" alt="" class="img-fluid">
                                <div class="media-body">
                                    <div>
                                        <p>Donna Seay</p>
                                        <span>2 minutes ago</span>
                                    </div><!-- d-flex -->
                                    <p>A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring.</p>
                                </div>
                            </div><!-- media -->
                        </a>
                        <!-- loop ends here -->
                        <a href="" class="media-list-link read">
                            <div class="media">
                                <img src="https://via.placeholder.com/500" alt="" class="img-fluid">
                                <div class="media-body">
                                    <div>
                                        <p>Samantha Francis</p>
                                        <span>3 hours ago</span>
                                    </div><!-- d-flex -->
                                    <p>My entire soul, like these sweet mornings of spring.</p>
                                </div>
                            </div><!-- media -->
                        </a>
                        <a href="" class="media-list-link read">
                            <div class="media">
                                <img src="https://via.placeholder.com/500" alt="" class="img-fluid">
                                <div class="media-body">
                                    <div>
                                        <p>Robert Walker</p>
                                        <span>5 hours ago</span>
                                    </div><!-- d-flex -->
                                    <p>I should be incapable of drawing a single stroke at the present moment...</p>
                                </div>
                            </div><!-- media -->
                        </a>
                        
                        <div class="dropdown-footer">
                            <a href=""><i class="fas fa-angle-down"></i> Show All Messages</a>
                        </div>
                    </div><!-- media-list -->
                </div><!-- dropdown-menu -->
            </div><!-- dropdown -->
            <div class="dropdown">
                <a href="" class="nav-link pd-x-7 pos-relative" data-toggle="dropdown">
                    <i class="icon ion-ios-bell-outline tx-24"></i>
                    <!-- start: if statement -->
                    <span class="square-8 bg-danger pos-absolute t-15 r-5 rounded-circle"></span>
                    <!-- end: if statement -->
                </a>
                <div class="dropdown-menu dropdown-menu-header">
                    <div class="dropdown-menu-label">
                        <label>Notifications</label>
                        <a href="">Mark All as Read</a>
                    </div><!-- d-flex -->

                    <div class="media-list">
                        <!-- loop starts here -->
                        <a href="" class="media-list-link read">
                            <div class="media">
                                <img src="https://via.placeholder.com/500" alt="" class="img-fluid">
                                <div class="media-body">
                                    <p class="noti-text"><strong>Suzzeth Bungaos</strong> tagged you and 18 others in a post.</p>
                                    <span>October 03, 2017 8:45am</span>
                                </div>
                            </div><!-- media -->
                        </a>
                        
                        <a href="" class="media-list-link read">
                            <div class="media">
                                <img src="https://via.placeholder.com/500" alt="" class="img-fluid">
                                <div class="media-body">
                                    <p class="noti-text"><strong>Julius Erving</strong> wants to connect with you on your conversation with <strong>Ronnie Mara</strong></p>
                                    <span>October 01, 2017 6:08pm</span>
                                </div>
                            </div><!-- media -->
                        </a>
                        <div class="dropdown-footer">
                            <a href=""><i class="fas fa-angle-down"></i> Show All Notifications</a>
                        </div>
                    </div><!-- media-list -->
                </div><!-- dropdown-menu -->
            </div><!-- dropdown -->
            <div class="dropdown">
                <a href="" class="nav-link nav-link-profile" data-toggle="dropdown">
                    <span class="logged-name hidden-md-down">Katherine</span>
                    <img src="https://via.placeholder.com/500" class="wd-32 rounded-circle img-fluid" alt="">
                    <span class="square-10 bg-success"></span>
                </a>
                <div class="dropdown-menu dropdown-menu-header wd-250">
                    <div class="tx-center">
                        <a href=""><img src="https://via.placeholder.com/500" class="wd-80 rounded-circle" alt=""></a>
                        <h6 class="logged-fullname">Katherine P. Lumaad</h6>
                        <p>youremail@domain.com</p>
                    </div>
                    <hr>
                    <ul class="list-unstyled user-profile-nav">
                        
                        <li><a href="{{route('admin.logout')}}" class="text-center"><i class="icon ion-power"></i> Sign Out</a></li>
                    </ul>
                </div><!-- dropdown-menu -->
            </div><!-- dropdown -->
        </nav>
        <!--<div class="navicon-right">-->
            <!--<a id="btnRightMenu" href="" class="pos-relative">-->
                <!--<i class="icon ion-ios-chatboxes-outline"></i>-->
                <!--&lt;!&ndash; start: if statement &ndash;&gt;-->
                <!--<span class="square-8 bg-danger pos-absolute t-10 r&#45;&#45;5 rounded-circle"></span>-->
                <!--&lt;!&ndash; end: if statement &ndash;&gt;-->
            <!--</a>-->
        <!--</div>&lt;!&ndash; navicon-right &ndash;&gt;-->
    </div><!-- fl-header-right -->
</div><!-- fl-header -->

resources/views/backend/include/lemon.blade.php
<li class="fl-menu-item">
    <a href="#" class="fl-menu-link with-sub">
        <i class="menu-item-icon icon ion-ios-photos-outline tx-20"></i>
        <span class="menu-item-label">Lemon</span>
    </a><!-- fl-menu-link -->
    <ul class="fl-menu-sub">
        <li class="sub-item"><a href="{{route('discount.index')}}" class="sub-link">Discount</a></li>
        <li class="sub-item"><a href="{{route('shipping-option.index')}}" class="sub-link">Shipping Option</a></li>
        {{--<li class="sub-item"><a href="{{route('shop-setting.index')}}" class="sub-link">Shop Setting</a></li>--}}
        <li class="sub-item"><a href="{{route('vendor-page.index')}}" class="sub-link">Vendor Pages</a></li>
        <li class="sub-item"><a href="{{route('translation-language.index')}}" class="sub-link">Translation Languages</a></li>
        <li class="sub-item"><a href="{{route('countries.index')}}" class="sub-link">Countries</a></li>
        <li class="sub-item"><a href="{{route('state.index')}}" class="sub-link">States</a></li>
        <li class="sub-item"><a href="{{route('city.index')}}" class="sub-link">Cities</a></li>
        <li class="sub-item"><a href="{{route('store-review.index')}}" class="sub-link">Store Review</a></li>
        <li class="sub-item"><a href="{{route('backend.order.view')}}" class="sub-link">Orders</a></li>
    </ul>
</li>

resources/views/backend/include/logo.blade.php
<div class="fl-logo">
    <a href="" class="d-flex">
        <!--<span>[</span>FEITS <i>LTD</i><span>]</span>-->
    <img class="brand-logo" alt="" src="{{asset('/public/backend/assets/img/logo-light-sm.png')}}">
        <h3 class="logo_text">FEITS Admin</h3>
    </a>
</div>

resources/views/backend/include/menu-responsive.blade.php
<aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
    <div class="p-3">
        {{--<h5>Title</h5>--}}
        {{--<p>Sidebar content</p>--}}
    </div>
</aside>

resources/views/backend/include/miraj.blade.php
<li class="fl-menu-item">
    <a href="#" class="fl-menu-link with-sub @if($routeName == 'payment-gateway.index') active @endif">
        <i class="menu-item-icon icon ion-ios-photos-outline tx-20"></i>
        <span class="menu-item-label">Payment Setting</span>
    </a><!-- fl-menu-link -->
    <ul class="fl-menu-sub">
        <li class="sub-item">
            <a href="{{route('payment-gateway.index')}}" class="sub-link">Payment Gateway</a>
        </li>
        <li class="sub-item">
            <a href="{{route('currencys.index')}}" class="sub-link">Currency</a>
        </li>
    </ul>
</li>

<li class="fl-menu-item">
    <a href="#" class="fl-menu-link with-sub @if($routeName == 'email-configuration.index') active @endif">
        <i class="menu-item-icon icon ion-ios-photos-outline tx-20"></i>
        <span class="menu-item-label">Email</span>
    </a><!-- fl-menu-link -->
    <ul class="fl-menu-sub">
        <li class="sub-item">
            <a href="{{route('email-configuration.index')}}" class="sub-link">Email Configuration</a>
        </li>
    </ul>
</li>

<li class="fl-menu-item">
    <a href="#" class="fl-menu-link with-sub @if($routeName == 'product.index') active @endif">
        <i class="menu-item-icon icon ion-ios-photos-outline tx-20"></i>
        <span class="menu-item-label">Product</span>
    </a><!-- fl-menu-link -->
    <ul class="fl-menu-sub">
        <li class="sub-item">
            <a href="{{route('products.create')}}" class="sub-link">Create Product</a>
        </li>
        <li class="sub-item">
            <a href="{{route('products.index')}}" class="sub-link">Product List</a>
        </li>
    </ul>
</li>

<li class="fl-menu-item">
    <a href="#" class="fl-menu-link with-sub @if($routeName == 'vendor-subscription-plan.index') active @endif">
        <i class="menu-item-icon icon ion-ios-photos-outline tx-20"></i>
        <span class="menu-item-label">Vendor</span>
    </a><!-- fl-menu-link -->
    <ul class="fl-menu-sub">
        <li class="sub-item">
            <a href="{{route('vendor-subscription-plan.index')}}" class="sub-link">Vendor Subscription Plan</a>
        </li>
        {{--<li class="sub-item">--}}
            {{--<a href="{{route('products.index')}}" class="sub-link">Product List</a>--}}
        {{--</li>--}}
    </ul>
</li>

resources/views/backend/include/msg.blade.php
{{--@if(Session::has('success'))--}}
{{--<div class="alert alert-success text-center">--}}
     {{--{{Session::get("success")}}.--}}
{{--</div>--}}
{{--@endif--}}

{{--@if(Session::has('warning'))--}}
    {{--<div class="alert alert-warning text-center">--}}
         {{--{{Session::get("warning")}}.--}}
    {{--</div>--}}
{{--@endif--}}

{{--@if(Session::has('error'))--}}
    {{--<div class="alert alert-danger text-center">--}}
         {{--{{Session::get("error")}}.--}}
    {{--</div>--}}
{{--@endif--}}

@if(Session::has('success'))
    <script>
        var msg ='{{ Session::get("success") }}';
        Swal.fire(msg, "", "success");
    </script>
@endif

@if(Session::has('warning'))
    <script>
        var msg ='{{Session::get("warning")}}';
        Swal.fire(msg, "", "warning");
    </script>
@endif

@if(Session::has('error'))
    <script>
        var msg ='{{Session::get("error")}}';
        Swal.fire(msg, "", "error");
    </script>
@endif

resources/views/backend/include/sidebar.blade.php
<div class="fl-sideleft sideleft-scrollbar">
    <label class="sidebar-label pd-x-10 mg-t-20 op-3">Navigation</label>
    <ul class="fl-sideleft-menu">
        @if(auth()->user()->user_type == 1)
            @include('backend.include.admin-menu')
            @endif

            @if(auth()->user()->user_type == 2)
                @include('backend.include.vendor-menu')
            @endif
    </ul><!-- fl-sideleft-menu -->

    <br>
</div><!-- fl-sideleft -->