routes/frontend.php
<?php
Route::get("/", "HomeController@index")->name('home.index');

Route::get('/page/{slug}', 'HomeController@customPage')->name('home.custom.page');

Route::get('/user-login', 'UserLoginController@loginView')->name('user.login');
Route::post('/user-login-submit', 'UserLoginController@loginSubmit')->name('user.login.submit');

Route::post('/user-registration-submit', 'UserController@store')->name('user.registration.submit');


Route::get('user/login/facebook', 'UserLoginController@redirectToProvider')->name('user.facebook.login');
Route::get('user/login/facebook/callback', 'UserLoginController@handleProviderCallback');

Route::get('user/login/google', 'UserLoginController@redirectToProviderGoogle')->name('user.google.login');
Route::get('user/login/google/callback', 'UserLoginController@handleProviderGoogleCallback');

Route::get('/product-detail/{slug}', 'frontend\ProductDetailController@index')->name('product.detail');

Route::group(['middleware' => 'authCeckUser'], function () {
    Route::resource("/user", "UserController");
    Route::get('/user-logout', 'UserLoginController@logout')->name('user.logout');

    Route::get('/become-vendor', 'frontend\UserDashboardController@BecomeVendor')->name('frontend.become.vendor');
    Route::post('/vendor/subscription', 'frontend\UserDashboardController@vendorSubscription')->name('frontend.vendor.subscription');
});

routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});

include('parvez.php');
include('frontend.php');

Route::get('/admin-login','AdminLoginController@loginView')->name('admin.login');
Route::post('/admin-login-submit','AdminLoginController@loginSubmit')->name('admin.login.submit');

Route::group(['middleware'=>'authCheck'],function (){
	
	 Route::get("/dashboard","DashboardController@index");

    Route::resource("/activity","ActivityController");

    Route::resource("/module","ModuleController");

    Route::resource("/role","RoleController");

    Route::resource("/user","UserController");

    Route::get('role-access',"RoleAccessController@index")->name('role.access');
    Route::post('roleAclSetup', 'RoleAccessController@roleAclSetup');
    Route::post('roleacl', 'RoleAccessController@save');

    Route::get('user-access', 'UserAccessController@index')->name('user.access');
    Route::post('userAclSetup', 'UserAccessController@userAclSetup');
    Route::post('useracl', 'UserAccessController@save');

    Route::get('/backend',function(){
        return view('backend.demo');
    });

    Route::get('/logout','AdminLoginController@logout')->name('admin.logout');

    Route::get('/dashboard',function(){
        return view('backend.demo');
    })->name('backend.dashboard');
    
    Route::get('/form',function(){
        return view('backend.form');
    });

    Route::resource("/discount", "DiscountController");
    Route::post('get-discount-user-list', 'DiscountController@getDiscountUserList')->name('discount-user.list');
    Route::resource("/shipping-option", "ShippingOptionController");
    Route::resource("/shop-setting", "ShopSettingController");
    Route::get("/show-logo-banner/{action}/{id}", "ShopSettingController@showLogoBanner")->name("show-logo-banner.show");
    Route::resource("/vendor-page", "VendorPageController");
    Route::resource("/translation-language", "TranslationLanguageController");
    Route::resource("/countries", "CountriesController");
    Route::resource("/state", "StateController");
    Route::resource("/city", "CityController");

    Route::resource("store-review","StoreReviewController");
    Route::get('orders','OrderController@index')->name('backend.order.view');
    Route::get('orders-details/{id}/{action?}','OrderController@orderDetails')->name('backend.order.details');
    Route::post('orders-status-change','OrderController@orderStatusChange')->name('backend.orders-status-change');

    Route::resource('payment-gateway','PaymentGatewayController');
    Route::resource('currencys','CurrencyController');
    Route::resource('email-configuration','EmailConfigurationController');
    Route::resource('products','ProductController');

    Route::get('products-gallery/{slug}','ProductGalleryController@galleryImage')->name('product.gallery');
    Route::post('products-gallery/product.gallery.store','ProductGalleryController@galleryImageStore')->name('product.gallery.store');
    Route::get('products-gallery/delete/{id}','ProductGalleryController@galleryImageDelete')->name('product.gallery.delete');

    //product route start
    Route::get('partho-product/create','ParthoProductController@ProductCreate')->name('product_create');
    Route::get('partho-product/list','ParthoProductController@ProductList')->name('product_list');
    Route::get('partho-product/details/{id}','ParthoProductController@productDetails')->name('product_details');
    Route::get('partho-product/edit/{id}','ParthoProductController@productEdit')->name('product_edit');
    Route::post('partho-product/store/','ParthoProductController@productStore')->name('product_store');
    Route::post('partho-product/update/','ParthoProductController@productUpdate')->name('product_update');
    Route::get('partho-import/product','ParthoProductController@importProduct')->name('import_product');
    //product route end

    Route::resource('vendor-subscription-plan','VendorSubscriptionPlansController');

//Ajax Route
    Route::post('get/subcategory','AjaxController@subCategory')->name('get.subcategory');
include('farhan.php');
});

app/Http/Controllers/CurrencyController.php
<?php

namespace App\Http\Controllers;

use App\Model\Currency;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

class CurrencyController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $currencys = Currency::orderBy('created_at')->paginate(20);
        return view('backend.currency.index',compact('currencys'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $currency = new Currency();
        return view('backend.currency.create',compact('currency'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $rules = [
            "name" => "required",
            "symbol" => "required",
            "multiplication_of_doller" => "required|numeric|min:1",
            "status" => "required"
        ];

        $message = [
            "multiplication_of_doller.required" => "Multiplication of USD is required",
        ];

        $validation = Validator::make($request->all(), $rules, $message);

        if ($validation->fails()) {
            return redirect()->back()->withInput()->withErrors($validation);
        } else {
            $currency = new Currency();
            $currency->name = $request->name;
            $currency->symbol = $request->symbol;
            $currency->multiplication_of_doller = $request->multiplication_of_doller;
            $currency->status = $request->status;

            if ($currency->save()){
                session()->flash('success','Currency information saved');
                return redirect('currencys');
            }else{
                session()->flash('error','Currency information not saved');
                return redirect()->back()->withInput();
            }
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Model\Currency  $currency
     * @return \Illuminate\Http\Response
     */
    public function show(Currency $currency)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Model\Currency  $currency
     * @return \Illuminate\Http\Response
     */
    public function edit(Currency $currency)
    {
        return view('backend.currency.edit',compact('currency'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Model\Currency  $currency
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Currency $currency)
    {
        $rules = [
            "name" => "required",
            "symbol" => "required",
            "multiplication_of_doller" => "required|numeric|min:1",
            "status" => "required"
        ];

        $message = [
            "multiplication_of_doller.required" => "Multiplication of USD is required",
        ];

        $validation = Validator::make($request->all(), $rules, $message);

        if ($validation->fails()) {
            return redirect()->back()->withInput()->withErrors($validation);
        } else {

            $currency->name = $request->name;
            $currency->symbol = $request->symbol;
            $currency->multiplication_of_doller = $request->multiplication_of_doller;
            $currency->status = $request->status;

            if ($currency->save()){
                session()->flash('success','Currency information updated');
                return redirect('currencys');
            }else{
                session()->flash('error','Currency information not updated');
                return redirect()->back()->withInput();
            }
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Model\Currency  $currency
     * @return \Illuminate\Http\Response
     */
    public function destroy(Currency $currency)
    {
        if ($currency->delete()){
            session()->flash('success','Currency deleted');
            return redirect('currencys');
        }else{
            session()->flash('error','Currency deleted');
            return redirect()->back()->withInput();
        }
    }
}

resources/views/backend/currency/_form.blade.php
@csrf
<div class="col-md-6">
    <div class="form-group row">
        <!-- Material input -->
        <label for="name" class="col-md-3 col-form-label">Name<span class="text-danger">*</span></label>
        <div class="col-md-9">
            <div class="md-form mt-0">
                <input type="text" name="name" class="form-control" id="name" value="{{old('name',$currency->name)}}" placeholder="Enter Currency Name" required>
                <span class="text-danger">@error('name') {{$message}} @enderror</span>
            </div>
        </div>
    </div>
</div>

<div class="col-md-6">
    <div class="form-group row">
        <!-- Material input -->
        <label for="symbol" class="col-md-3 col-form-label">Symbol<span class="text-danger">*</span></label>
        <div class="col-md-9">
            <div class="md-form mt-0">
                <input type="text" name="symbol" class="form-control" id="symbol" value="{{old('symbol',$currency->symbol)}}" placeholder="Enter Currency Symbol" required>
                <span class="text-danger">@error('symbol') {{$message}} @enderror</span>
            </div>
        </div>
    </div>
</div>

<div class="col-md-6">
    <div class="form-group row">
        <!-- Material input -->
        <label for="multiplication_of_doller" class="col-md-3 col-form-label">Multiplication of USD<span class="text-danger">*</span></label>
        <div class="col-md-9">
            <div class="md-form mt-0">
                <input type="text"   name="multiplication_of_doller" class="form-control" id="multiplication_of_doller" value="{{old('multiplication_of_doller',$currency->multiplication_of_doller)}}" placeholder="Enter Multiplication of USD Amount" data-parsley-type="number" data-parsley-min="1" required>
                <span class="text-danger">@error('multiplication_of_doller') {{$message}} @enderror</span>
            </div>
        </div>
    </div>
</div>



<div class="col-6">
    <div class="form-group row">
        <label for="status" class="col-md-3 col-form-label">Status<span class="text-danger">*</span></label>
        <div class="col-md-9">
            <select name="status" class="browser-default custom-select form-control" id="status" required>
                <option @if(old('status') == null  && $currency->status == null) selected @endif>Select One</option>
                <option @if(old('status',$currency->status) == 0) selected @endif value="0">Inactive</option>
                <option @if(old('status',$currency->status) == 1) selected @endif value="1">Active</option>
            </select>
            <span class="text-danger">@error('status') {{$message}} @enderror</span>
        </div>
    </div>
</div>

<div class="col-md-12 text-center mt-3">
    <a href="{{url()->previous()}}" class="btn btn-danger btn-rounded waves-effect waves-light">Cancel</a>
    <button type="submit" class="btn btn-primary btn-rounded waves-effect waves-light">Submit</button>
</div>

resources/views/backend/currency/create.blade.php
@extends('backend.layout.layout')
@section('title','Payment Gateway Create')

@section('content')
    <div class="fl-page-section">
        <div class="fl-input-section">
            <div class="card card_main_body">

                <div class="card-header">
                    <h4>
                        <i class="fas fa-plus-circle"></i>
                        Create Currency
                    </h4>
                </div>
                <div class="card-body">
                    <div class="fl-form">
                        <div class="form">
                            <form method="post" action="{{route('currencys.store')}}" data-parsley-validate>
                            <div class="row">
                               @include('backend.currency._form')
                            </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    @endsection

resources/views/backend/currency/edit.blade.php
@extends('backend.layout.layout')
@section('title','Payment Gateway Create')

@section('content')
    <div class="fl-page-section">
        <div class="fl-input-section">
            <div class="card card_main_body">

                <div class="card-header">
                    <h4>
                        <i class="fas fa-plus-circle"></i>
                        Edit Payment Gateway
                    </h4>
                </div>
                <div class="card-body">
                    <div class="fl-form">
                        <div class="form">
                            <form method="post" action="{{route('currencys.update',$currency->id)}}" data-parsley-validate>
                                @method('put')
                            <div class="row">
                                @include('backend.currency._form')
                            </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    @endsection

resources/views/backend/currency/index.blade.php
@extends('backend.layout.layout')
@section('title','Payment Gateway')

@section('content')
    <div class="fl-page-section">
        <div class="fl-pagetitle">
            <div>
                <h4> <i class="icon icon ion-ios-bookmarks-outline"></i>Payment Gateway List</h4>
            </div>
            <div class="pagetitle-btn">
                <a href="{{route('currencys.create')}}" class="btn  btn-info btn-sm custom-btn-1 btn-1 tx-11 tx-uppercase pd-y-8 pd-x-18 tx-mont tx-medium"> <i class="fas fa-plus-circle"></i> Add New</a>
            </div>
        </div>
        <div class="fl-table-section">
            <div class="table_body">
                <div class="table-responsive">
                    <table class="table fl_table">
                        <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Name</th>
                            <th scope="col">Currency Symbol</th>
                            <th scope="col">Multiplication of USD</th>
                            <th scope="col">Status</th>
                            <th scope="col">Created At</th>
                            <th scope="col">Updated At</th>
                            <th scope="col">Action</th>
                        </tr>
                        </thead>
                        <tbody>
                        @php
                        $i = CustomClass::paginationSerial($currencys);
                        @endphp
                        @forelse($currencys as $currency)
                        <tr>
                            <td>{{$i++}}</td>
                            <td>{{$currency->name}}</td>
                            <td>{{$currency->symbol}}</td>
                            <td>{{$currency->multiplication_of_doller}}</td>
                            <td class="text-center">
                                @if($currency->status == 0)
                                    <span class="btn btn-sm btn-danger p-1">Inactive</span>
                                    @else
                                    <span class="btn btn-sm btn-success p-1">Active</span>
                                @endif
                            </td>
                            <td>{{date('d-m-Y',strtotime($currency->created_at))}}</td>
                            <td>{{date('d-m-Y',strtotime($currency->updated_at))}}</td>
                            <td>
                                <form method="post" action="{{ route('currencys.destroy',$currency->id) }}">

                                <a class="status btn btn-sm fl_btn btn-warning" title="" href="{{ route('currencys.edit',$currency->id) }}"><i class="fa fa-edit" title="Edit"></i></a>
@csrf
                                    @method('delete')
                                <button type="submit" class="delete status btn btn-sm fl_btn btn-danger" title="Delete"><i class="fa fa-trash"></i></button>

                                </form>
                            </td>
                        </tr>
                            @empty
                            <tr>
                                <td colspan="7">
                                    <h2 class="text-center">No Currency Found</h2>
                                </td>
                            </tr>
                        @endforelse

                        </tbody>
                        @if(!empty($currencys->links()))
                        <tfoot>
                        <tr>
                            <td colspan="8">
                                {{$currencys->links()}}
                            </td>
                        </tr>
                        </tfoot>
                        @endif
                    </table>
                </div>
            </div>

        </div>
    </div>
    @endsection