routes/frontend.php
<?php
Route::get("/", "HomeController@index")->name('home.index');

Route::get('/page/{slug}', 'HomeController@customPage')->name('home.custom.page');

Route::get('/user-login', 'UserLoginController@loginView')->name('user.login');
Route::post('/user-login-submit', 'UserLoginController@loginSubmit')->name('user.login.submit');

Route::post('/user-registration-submit', 'UserController@store')->name('user.registration.submit');


Route::get('user/login/facebook', 'UserLoginController@redirectToProvider')->name('user.facebook.login');
Route::get('user/login/facebook/callback', 'UserLoginController@handleProviderCallback');

Route::get('user/login/google', 'UserLoginController@redirectToProviderGoogle')->name('user.google.login');
Route::get('user/login/google/callback', 'UserLoginController@handleProviderGoogleCallback');

Route::get('/product-detail/{slug}', 'frontend\ProductDetailController@index')->name('product.detail');

Route::group(['middleware' => 'authCeckUser'], function () {
    Route::resource("/user", "UserController");
    Route::get('/user-logout', 'UserLoginController@logout')->name('user.logout');

    Route::get('/become-vendor', 'frontend\UserDashboardController@BecomeVendor')->name('frontend.become.vendor');
    Route::post('/vendor/subscription', 'frontend\UserDashboardController@vendorSubscription')->name('frontend.vendor.subscription');
});

routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});

include('parvez.php');
include('frontend.php');

Route::get('/admin-login','AdminLoginController@loginView')->name('admin.login');
Route::post('/admin-login-submit','AdminLoginController@loginSubmit')->name('admin.login.submit');

Route::group(['middleware'=>'authCheck'],function (){
	
	 Route::get("/dashboard","DashboardController@index");

    Route::resource("/activity","ActivityController");

    Route::resource("/module","ModuleController");

    Route::resource("/role","RoleController");

    Route::resource("/user","UserController");

    Route::get('role-access',"RoleAccessController@index")->name('role.access');
    Route::post('roleAclSetup', 'RoleAccessController@roleAclSetup');
    Route::post('roleacl', 'RoleAccessController@save');

    Route::get('user-access', 'UserAccessController@index')->name('user.access');
    Route::post('userAclSetup', 'UserAccessController@userAclSetup');
    Route::post('useracl', 'UserAccessController@save');

    Route::get('/backend',function(){
        return view('backend.demo');
    });

    Route::get('/logout','AdminLoginController@logout')->name('admin.logout');

    Route::get('/dashboard',function(){
        return view('backend.demo');
    })->name('backend.dashboard');
    
    Route::get('/form',function(){
        return view('backend.form');
    });

    Route::resource("/discount", "DiscountController");
    Route::post('get-discount-user-list', 'DiscountController@getDiscountUserList')->name('discount-user.list');
    Route::resource("/shipping-option", "ShippingOptionController");
    Route::resource("/shop-setting", "ShopSettingController");
    Route::get("/show-logo-banner/{action}/{id}", "ShopSettingController@showLogoBanner")->name("show-logo-banner.show");
    Route::resource("/vendor-page", "VendorPageController");
    Route::resource("/translation-language", "TranslationLanguageController");
    Route::resource("/countries", "CountriesController");
    Route::resource("/state", "StateController");
    Route::resource("/city", "CityController");

    Route::resource("store-review","StoreReviewController");
    Route::get('orders','OrderController@index')->name('backend.order.view');
    Route::get('orders-details/{id}/{action?}','OrderController@orderDetails')->name('backend.order.details');
    Route::post('orders-status-change','OrderController@orderStatusChange')->name('backend.orders-status-change');

    Route::resource('payment-gateway','PaymentGatewayController');
    Route::resource('currencys','CurrencyController');
    Route::resource('email-configuration','EmailConfigurationController');
    Route::resource('products','ProductController');

    Route::get('products-gallery/{slug}','ProductGalleryController@galleryImage')->name('product.gallery');
    Route::post('products-gallery/product.gallery.store','ProductGalleryController@galleryImageStore')->name('product.gallery.store');
    Route::get('products-gallery/delete/{id}','ProductGalleryController@galleryImageDelete')->name('product.gallery.delete');

    //product route start
    Route::get('partho-product/create','ParthoProductController@ProductCreate')->name('product_create');
    Route::get('partho-product/list','ParthoProductController@ProductList')->name('product_list');
    Route::get('partho-product/details/{id}','ParthoProductController@productDetails')->name('product_details');
    Route::get('partho-product/edit/{id}','ParthoProductController@productEdit')->name('product_edit');
    Route::post('partho-product/store/','ParthoProductController@productStore')->name('product_store');
    Route::post('partho-product/update/','ParthoProductController@productUpdate')->name('product_update');
    Route::get('partho-import/product','ParthoProductController@importProduct')->name('import_product');
    //product route end

    Route::resource('vendor-subscription-plan','VendorSubscriptionPlansController');

//Ajax Route
    Route::post('get/subcategory','AjaxController@subCategory')->name('get.subcategory');
include('farhan.php');
});

app/Http/Controllers/ShippingOptionController.php
<?php

namespace App\Http\Controllers;

use App\Model\ShippingOption;
use Illuminate\Http\Request;
use App\CustomClass\OwnLibrary;
use Illuminate\Support\Str;
use App\Events\ShippingOptionEvnt;
use Illuminate\Support\Facades\Validator;
use Illuminate\Validation\Rule;
use Illuminate\Support\Facades\Auth;

class ShippingOptionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $shipping_options = ShippingOption::with('createdBy','updatedBy');
        if(Auth::user()->role_id == 10){
            $shipping_options->where("vendor_id","=",Auth::user()->id);
        }
        $shipping_options = $shipping_options->orderBy("id")->paginate(20);
        return view('backend.shipping-option.index',compact('shipping_options'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backend.shipping-option.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $rules = [
            'method_name' => [
                'required',
                'min:2',
                'max:250',
                Rule::unique('shipping_options')->where(function($query) {
                    (Auth::user()->role_id==10) ? $query->where('vendor_id', '=', Auth::id()) : $query->whereNull('vendor_id');
                })
            ],
            //"method_name" => "required|min:2|max:250|unique:shipping_options",
            "charge" => "required|numeric|min:1|max:999999999",
        ];

        $message = [
            "method_name.required" => "The Shipping Name is required.",
            "method_name.max" => "The Shipping Name may not be greater than 250 characters.",
            "method_name.min" => "The Shipping Name may not be lass than 2 characters.",
            "charge.required" => "Charge is required.",
            "charge.numeric" => "Charge should be numeric number.",
            "charge.max" => "Charge may not be greater than 50.",
            "charge.min" => "Charge may not be lass than 1.",
        ];

        $validation = Validator::make($request->all(), $rules, $message);

        if ($validation->fails()) {
            return redirect()->back()->withInput()->withErrors($validation);
        } else {

            $data = [
                'request' => $request,
                'id' => null,
            ];

            $result = event(new ShippingOptionEvnt($data));

            if ($result) {
                session()->flash("success", "Shipping option successfully created");
                return redirect()->route('shipping-option.index');
            } else {
                session()->flash("error", "Shipping option not created");
                return redirect()->back();
            }

        }

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Model\Discount  $discount
     * @return \Illuminate\Http\Response
     */
    public function show(Discount $discount)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Model\Discount  $discount
     * @return \Illuminate\Http\Response
     */
    public function edit(ShippingOption $shippingOption)
    {
        return view("backend.shipping-option.edit",compact('shippingOption'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Model\Discount  $discount
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $rules = [
            'method_name' => [
                'required',
                'min:2',
                'max:250',
                Rule::unique('shipping_options')->ignore($id)->where(function($query) use($id) {
                    (Auth::user()->role_id==10) ? $query->where('vendor_id', '=', Auth::id()) : $query->whereNull('vendor_id');
                })
            ],
            //"method_name" => "required|min:2|max:250|unique:shipping_options,method_name," . $id,
            "charge" => "required|numeric|min:1|max:999999999",
        ];

        $message = [
            "method_name.required" => "The Shipping Name is required.",
            "method_name.max" => "The Shipping Name may not be greater than 250 characters.",
            "method_name.min" => "The Shipping Name may not be lass than 2 characters.",
            "charge.required" => "Charge is required.",
            "charge.numeric" => "Charge should be numeric number.",
            "charge.max" => "Charge may not be greater than 50.",
            "charge.min" => "Charge may not be lass than 1.",
        ];

        $validation = Validator::make($request->all(), $rules, $message);

        if ($validation->fails()) {
            return redirect()->back()->withInput()->withErrors($validation);
        } else {
            $data = [
                'request' => $request,
                'id' => $id,
            ];

            $result = event(new ShippingOptionEvnt($data));

            if($result){
                session()->flash('success','Shipping option updated');
                return redirect()->route('shipping-option.index');
            }else{
                session()->flash('error','Shipping option Not updated');
                return redirect()->back()->withInput();
            }
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Model\Discount  $discount
     * @return \Illuminate\Http\Response
     */
    public function destroy(ShippingOption $shippingOption)
    {
        if ($shippingOption->delete()) {
            session()->flash("success", "Shipping Option Deleted");
            return redirect()->back();
        } else {
            session()->flash("error", "Shipping Option Not Deleted");
            return redirect()->back();
        }
    }

}

resources/views/backend/shipping-option/create.blade.php
@extends('backend.layout.layout')
@section("title","Create Shipping Option")
@section('content')
    <div class="fl-page-section">
        <div class="fl-input-section">
            <div class="card card_main_body">

                <div class="card-header">
                    <h4>
                        <i class="fas fa-plus-circle"></i>
                        Create Shipping Option
                    </h4>
                </div>
                <form method="post" action="{{route("shipping-option.store")}}" class="submit-form" id="discount_form" enctype="multipart/form-data" data-parsley-validate>
                    @csrf
                    <div class="card-body">
                        <div class="fl-form">
                            <div class="form">
                                <div class="row">
                                    <div class="col-md-7">
                                        <div class="row">
                                            <div class="col-md-12">
                                                <div class="form-group row">
                                                    <label for="method_name" class="col-md-4 col-form-label">Shipping Name <span style="color:red">*</span></label>
                                                    <div class="col-md-8">
                                                        <div class="md-form mt-0">
                                                            <input type="text" class="form-control" name="method_name" id="method_name" placeholder="Enter option name" value="{{old("method_name")}}" data-parsley-trigger="keyup" data-parsley-minlength="1" data-parsley-maxlength="250" data-parsley-required-message="The method name is required." required>
                                                            <span class="text-danger"> {{$errors->has("method_name") ? $errors->first("method_name") : ""}} </span>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>

                                            <div class="col-md-12">
                                                <div class="form-group row">
                                                    <!-- Material input -->
                                                    <label for="charge" class="col-md-4 col-form-label">Shipping Charge <span style="color:red">*</span></label>
                                                    <div class="col-md-8">
                                                        <div class="md-form mt-0">
                                                            <input type="text" class="form-control" id="charge" name="charge" placeholder="Enter shipping charge" value="{{old("charge")}}" data-parsley-trigger="keyup" data-parsley-minlength="1" data-parsley-maxlength="15" step="100" data-parsley-validation-threshold="1" data-parsley-type="number"data-parsley-required-message="The charge is required." required>
                                                            <span class="text-danger"> {{$errors->has("charge") ? $errors->first("charge") : ""}} </span>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>

                                            <div class="col-md-12">
                                                <div class="form-group row">
                                                    <label for="status" class="col-md-4 col-form-label">Status <span style="color:red">*</span></label>
                                                    <div class="col-md-8">
                                                        <select class="browser-default custom-select form-control" name="status">
                                                            <option value="1" @if(old('status')==1) selected @endif>Active</option>
                                                            <option value="0" @if(old('status') AND old('status')==0) selected @endif>Inactive</option>
                                                        </select>
                                                        <span class="text-danger"> {{$errors->has("status") ? $errors->first("status") : ""}} </span>
                                                    </div>
                                                </div>
                                            </div>

                                            <div class="col-md-12 text-right mt-3">
                                                <button type="submit" class="btn btn-info btn-rounded waves-effect waves-light submit_button">Save</button>
                                                <button type="button" class="btn btn-danger btn-rounded waves-effect waves-light cancel">Cancel</button>
                                                <div class="spinner">&nbsp;</div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>

            </div>
        </div>
    </div>
@endsection

@section('js')
    <script>
        $(document).ready(function(){

            $('#users').select2({
                placeholder: "Select users"
            });

            $(document).on("change","#coupon_type", function(){
                var coupon_type = $(this).val();
                if(coupon_type=='specific_user'){
                    // $("#user_div").show();
                    $("#user_div").removeClass("invisible");
                    $('#users').attr('required', 'required').parsley();
                }else{
                    // $("#user_div").hide();
                    $("#user_div").addClass("invisible");
                    $('#users').removeAttr('required').parsley();
                }
            });

            $(".submit-form").submit(function(e){
                if( $(this).parsley().validate() ){
                    $('.spinner:last').show();
                    $('.submit_button').attr('disabled','disabled');
                }

            });

        });
    </script>
@endsection

resources/views/backend/shipping-option/edit.blade.php
@extends('backend.layout.layout')
@section("title","Update Shipping Option")
@section('content')
    <div class="fl-page-section">
        <div class="fl-input-section">
            <div class="card card_main_body">

                <div class="card-header">
                    <h4>
                        <i class="fas fa-plus-circle"></i>
                        Update Shipping Option
                    </h4>
                </div>
                <form method="post" action="{{route("shipping-option.update",$shippingOption->id)}}" class="submit-form" id="discount_form" enctype="multipart/form-data" data-parsley-validate>
                    @method('put')
                    @csrf
                    <div class="card-body">
                        <div class="fl-form">
                            <div class="form">
                                <div class="row">
                                    <div class="col-md-7">
                                        <div class="row">
                                            <div class="col-md-12">
                                                <div class="form-group row">
                                                    <label for="method_name" class="col-md-4 col-form-label">Shipping Name <span style="color:red">*</span></label>
                                                    <div class="col-md-8">
                                                        <div class="md-form mt-0">
                                                            <input type="text" class="form-control" name="method_name" id="method_name" placeholder="Enter option name" value="{{old("method_name",$shippingOption->method_name)}}" data-parsley-trigger="keyup" data-parsley-minlength="1" data-parsley-maxlength="250" data-parsley-required-message="The method name is required." required>
                                                            <span class="text-danger"> {{$errors->has("method_name") ? $errors->first("method_name") : ""}} </span>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>

                                            <div class="col-md-12">
                                                <div class="form-group row">
                                                    <!-- Material input -->
                                                    <label for="charge" class="col-md-4 col-form-label">Shipping Charge <span style="color:red">*</span></label>
                                                    <div class="col-md-8">
                                                        <div class="md-form mt-0">
                                                            <input type="text" class="form-control" id="charge" name="charge" placeholder="Enter shipping charge" value="{{old("charge",$shippingOption->charge)}}" data-parsley-trigger="keyup" data-parsley-minlength="1" data-parsley-maxlength="15" step="100" data-parsley-validation-threshold="1" data-parsley-type="number"data-parsley-required-message="The charge is required." required>
                                                            <span class="text-danger"> {{$errors->has("charge") ? $errors->first("charge") : ""}} </span>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>

                                            <div class="col-md-12">
                                                <div class="form-group row">
                                                    <label for="status" class="col-md-4 col-form-label">Status <span style="color:red">*</span></label>
                                                    <div class="col-md-8">
                                                        <select class="browser-default custom-select form-control" name="status">
                                                            <option value="1" @if(old("status", $shippingOption->status)==1) selected @endif>Active</option>
                                                    <option value="0" @if(old("status", $shippingOption->status)==0) selected @endif>Inactive</option>
                                                        </select>
                                                        <span class="text-danger"> {{$errors->has("status") ? $errors->first("status") : ""}} </span>
                                                    </div>
                                                </div>
                                            </div>

                                            <div class="col-md-12 text-right mt-3">
                                                <button type="submit" class="btn btn-info btn-rounded waves-effect waves-light submit_button">Save</button>
                                                <button type="button" class="btn btn-danger btn-rounded waves-effect waves-light cancel">Cancel</button>
                                                <div class="spinner">&nbsp;</div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>

            </div>
        </div>
    </div>
@endsection

@section('js')
    <script>
        $(document).ready(function(){

            $('#users').select2({
                placeholder: "Select users"
            });

            $(document).on("change","#coupon_type", function(){
                var coupon_type = $(this).val();
                if(coupon_type=='specific_user'){
                    // $("#user_div").show();
                    $("#user_div").removeClass("invisible");
                    $('#users').attr('required', 'required').parsley();
                }else{
                    // $("#user_div").hide();
                    $("#user_div").addClass("invisible");
                    $('#users').removeAttr('required').parsley();
                }
            });

            $(".submit-form").submit(function(e){
                if( $(this).parsley().validate() ){
                    $('.spinner:last').show();
                    $('.submit_button').attr('disabled','disabled');
                }

            });

        });
    </script>
@endsection